### PR TITLE
Upgrade k8s library to 0.17.0

### PR DESCRIPTION
**Pull request by sa-mao**
Upgrade k8s Library to 0.17.0 in order to introduce the ServiceAccount class.

### CODE REVIEW

**Review by oyvindio — COMMENTED** [review]
This looks good, but I'd like to get a full CI build before merging. Because of #131 that doesn't seem to work for branches from forks, so I'll push this to a branch to get a CI build in the meantime.

**Comment by PerGon** [comment]
In #131 @mortenlj says that using /sem-approve would allow to run the required CI jobs to validate this PR? Can we try that?

**Comment by mortenlj** [comment]
> In #131 @mortenlj says that using /sem-approve would allow to run the required CI jobs to validate this PR? Can we try that?

Looks like it still doesn't work :slightly_frowning_face: 

Would probably be helpful if someone took some time to properly investigate this, but I don't have the time.

**Comment by PerGon** [comment]
Thanks for checking.

I've created a branch which contains the same code as in here and it's rebased. CI checks are still failing but seems to be they fail in a way that is unrelated to the PR. I'm a bit puzzled 🤔

**Comment by PerGon** [comment]
@sa-mao can you rebase with master? The CI tests have now been fixed on master and we should see this PR checks coming up green 🟢

**Comment by PerGon** [comment]
@oyvindio do you know why, after the rebase, the CI jobs where not triggered?

**Comment by oyvindio** [comment]
> @oyvindio do you know why, after the rebase, the CI jobs where not triggered?

Because it is a forked branch, it needs to be approved with a /sem-approve comment. This actually seems to work now as I see a CI build was triggered by my previous comment — it didn't work previously

**Review by PerGon — APPROVED** [review]
lgtm

**Comment by PerGon** [comment]
@oyvindio thanks a bunch!
This now looks good to me. Can it be merged?

**Review by oyvindio — APPROVED** [review]

**Pull request merged**
