### PR TITLE
72 Allow separate service account per application

### PR DESCRIPTION
**Pull request by sa-mao**
[WIP]

### CODE REVIEW

**Comment by sa-mao** [comment]
Besides from allowing arbitrary service accounts per app there is actually no benefit. Do you think that would be less useful?

**Comment by mortenlj** [comment]
There is the balance between flexibility and complexity to think about. If fiaas were to provide every feature of kubernetes in fiaas.yaml, it has no purpose other than complicate things. So for every new field we introduce, it is important to think about why we are adding this field, and do we really need it. 

And while this change won't be the one that suddenly makes fiaas.yaml too complex, that can be said of any addition, until one day we find that it is too complex.

For this use case, I think the mentioned discussion found that using a service account named the same as the app should work fine for most uses (and importantly, all the ones we knew needed to be solved), and adding an option nobody has asked for is probably not worth it.

**Comment by sa-mao** [comment]
I would argue that in this case, allowing custom service accounts to be created outside of FIAAS and then mounted by introducing a new field is far better that creating service accounts by FDD, then trying to update them manually or by any other mean to inject whatever we need later on (I'm thinking here of the annotation with AWS IAM role Arn).

There is also the reusability argument (although I acknowledge it might be controversial in this case).

The way I see it: this is a perfect balance between flexibility and complexity.

**Comment by xavileon** [comment]
> I would argue that in this case, allowing custom service accounts to be created outside of FIAAS and then mounted by introducing a new field is far better that creating service accounts by FDD

That doesn't mean it is not possible with the approach described in #72 I think. You could create a service account outside of FDD following the naming convention (same as the app name) and FDD could pick this up as is (the same way FDD does with externally created secrets). That probably imposes some restrictions on the flow when creating an app, but nothing that having a custom name doesn't impose anyway. It's more about convention over configuration than anything else.

Is there any use case in which the name of the service account actually matters?

**Comment by tg90nor** [comment]
> That doesn't mean it is not possible with the approach described in #72 I think. You could create a service account outside of FDD following the naming convention (same as the app name) and FDD could pick this up as is (the same way FDD does with externally created secrets). That probably imposes some restrictions on the flow when creating an app, but nothing that having a custom name doesn't impose anyway. It's more about convention over configuration than anything else.

What about when FDD does not find a service account with the same name as the app? Should it fall back to `default`, or create a new SA?

**Comment by xavileon** [comment]
> > That doesn't mean it is not possible with the approach described in #72 I think. You could create a service account outside of FDD following the naming convention (same as the app name) and FDD could pick this up as is (the same way FDD does with externally created secrets). That probably imposes some restrictions on the flow when creating an app, but nothing that having a custom name doesn't impose anyway. It's more about convention over configuration than anything else.
> 
> What about when FDD does not find a service account with the same name as the app? Should it fall back to `default`, or create a new SA?

I'd say it should create a new SA if FDD is configured to have a per-app service account. This would allow creating the SA before the app or modify it afterwards, depending on the different needs and workflows?

**Comment by sa-mao** [comment]
In that case, I agree.

**Comment by oyvindio** [comment]
This feature was merged in #159

**Pull request closed without merging**
